export interface Prematricula {
  nombre: string,
    apellidos: string,
    lugarDeNacimiento: string,
    fechaDeNacimiento: string,
    tipoDeDocumentoDeIdentidad: string,
    numeroDeDocumentoDeIdentidad: number,
    grupoSanguineo: string,
    sexo: string,
    gradoAlQueAspira: string,
    repiteAOAcadMico: string,
    barrio: string,
    direcciN: string,
    ciudad: string,
    telFono: number,
    email: string,
    religiNQueProfesa: string,
    eps: string,
    nombreDeLaMadre: string,
    apellidosDeLaMadre: string,
    tipoDeDocumentoDeIdentidadDeLaMadre: string,
    numeroDeDocumentoDeIdentidadDeLaMadre: number,
    lugarDeExpediciNDelDocumentoDeLaMadre: string,
    edadDeLaMadre: number,
    direcciNDeLaMadre: string,
    telFonoDeLaMadre: number,
    nivelDeEstudioDeLaMadre: string,
    ocupaciNActualDeLaMadre: string,
    cargoQueOcupaLaMadre: string,
    empresaDondeLaboraLaMadre: string,
    nombreDelPadre: string,
    apellidosDelPadre: string,
    tipoDeDocumentoDeIdentidadDelPadre: string,
    numeroDeDocumentoDeIdentidadDelPadre: number,
    lugarDeExpediciNDelDocumentoDelPadre: string,
    edadDelPadre: number,
    direcciNDelPadre: string,
    telFonoDelPadre: number,
    nivelDeEstudioDelPadre: string,
    ocupaciNActualDelPadre: string,
    cargoQueOcupaElPadre: string,
    empresaDondeLaboraElPadre: string,
    quienSerElAcudienteDelEstudiante: string,
    nombreDelAcudiente:null,
    apellidosDelAcudiente:null,
    tipoDeDocumentoDeIdentidadDelAcudiente:null,
    numeroDeDocumentoDeIdentidadDelAcudiente:null,
    lugarDeExpediciNDelDocumentoDelAcudiente:null,
    edadDelAcudiente:null,
    direcciNDelAcudiente:null,
    telFonoDelAcudiente:null,
    nivelDeEstudioDelAcudiente:null,
    ocupaciNActualDelAcudiente:null,
    cargoQueOcupaElAcudiente:null,
    empresaDondeLaboraElAcudiente:null
}
